[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = -Os
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit ILI9341
    adafruit/Adafruit GFX Library
    SPI
    Wire
    arduino-libraries/SD
    Bounce2
    paulstoffregen/OneWire
    milesburton/DallasTemperature
